Implement grip threshold profile setting
XRTK/Lumin pull request #98
Opened 2021-01-23 20:49 UTC by FejZa

## Overview

https://github.com/XRTK/XRTK-Core/pull/767

2021-01-25 14:27 UTC, StephenHodgson commented on XRTK.Lumin/Packages/com.xrtk.lumin/package.json
> +  "version": "0.2.3",
Version bump too far. Should bc 0.2.2

2021-01-25 14:28 UTC, StephenHodgson commented
/azp run

2021-01-25 14:30 UTC, StephenHodgson commented on XRTK.Lumin/Packages/com.xrtk.lumin/package.json
> +    "com.xrtk.core": "0.2.3"
Let's revert the package dependency change for now as there aren't any breaking changes. That way we can get the builds to pass and merge this into development first and do our usual workflow

2021-01-25 14:30 UTC, StephenHodgson requested changes
See comments

2021-01-25 23:57 UTC, StephenHodgson commented
/azp run

2021-01-26 10:59 UTC, FejZa commented
/azp run

2021-01-26 11:01 UTC, FejZa commented
I am not seeing any comments on this PR? What's wrong with it?

2021-01-26 13:18 UTC, StephenHodgson approved these changes

2021-01-26 13:18 UTC, merged